export const types = {
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_STARTED: 'REGISTER_USER_STARTED',
  REGISTER_USER_SUCCESSFULL: 'REGISTER_USER_SUCCESSFULL',
  REGISTER_USER_FAILED: 'REGISTER_USER_FAILED',
};
