export const types = {
  GET_WORK_STARTED: 'GET_WORK_STARTED',
  GET_WORK: 'GET_WORK',
  GET_WORK_SUCCESSFULL: 'GET_WORK_SUCCESSFULL',
  GET_WORK_FAILED: 'GET_WORK_FAILED',

  POST_WORK_STARTED: 'POST_WORK_STARTED',
  POST_WORK: 'POST_WORK',
  POST_WORK_SUCCESSFULL: 'POST_WORK_SUCCESSFULL',
  POST_WORK_FAILED: 'POST_WORK_FAILED',

  PUT_WORK_STARTED: 'PUT_WORK_STARTED',
  PUT_WORK: 'PUT_WORK',
  PUT_WORK_SUCCESSFULL: 'PUT_WORK_SUCCESSFULL',
  PUT_WORK_FAILED: 'PUT_WORK_FAILED',

  DELETE_WORK_STARTED: 'DELETE_WORK_STARTED',
  DELETE_WORK: 'DELETE_WORK',
  DELETE_WORK_SUCCESSFULL: 'DELETE_WORK_SUCCESSFULL',
  DELETE_WORK_FAILED: 'DELETE_WORK_FAILED',
};
